### ISSUE TITLE
Consider alternative formats

### ISSUE THREAD

**Issue by appetrosyan** [Greybeard-Entertainment/pages#2]
I hate markdown. 

I have done a survey of the kinds of languages that we could use and here's my conclusion in order of preference;
1. Could just use HTML. How we generate it is irrelevant, so we get more freedom in how we generate the thing, and fine control for the generated content. 
2. Use Org, either directly, via plugin, or just convert it to HTML and publish that. Works for some blogs but not others. 
3. Consider LaTeX. I don't know if there are SSGs that work with LaTeX. 
4. Consider `typst`. No SSGs work with it, but I could write a  plugin in Rust and compile it to WASM and push to `npm`. Might need to move to `Vuepress` as `Vitepress` doesn't exactly have a plugin API.

**Comment by 6r1d** [comment]
I like what Typst looks like, although what worries me is having the whole stack easily available. I doubt the plugin would be hard to adapt.

What are the issues with Org?

**Comment by appetrosyan** [comment]
> What are the issues with Org?

Mainly that nobody supports it. We'd have to set up a pipeline to export the `org` files before publishing. 

It can solve a few problems for us, though. 
- Bibtex for citations
- Automatic referencing and back-referencing in HTML (it does footnotes without Markdown-it). 
- Equations (not tested)
- Language-based rich markup

It doesn't offer much of an advantage, and I'd rather not have a `set-up-emacs` action in the CI. Particularly given how many variables would need to be set for the export to work properly. `pandoc` is not an option, because it throws away some of the markup.

**Comment by appetrosyan** [comment]
Closed via #8
